site_name: bootstrap-select
site_description: Bootstrap-select is a jQuery plugin that utilizes Bootstrap's dropdown.js to style and bring additional functionality to normal select boxes.
repo_url: https://github.com/silviomoreto/bootstrap-select
theme: bootstrap
theme_dir: custom_theme
extra_css:
- //cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.0/css/bootstrap-select.min.css
- css/custom.css
extra_javascript:
- //cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.0/js/bootstrap-select.min.js
pages:
- Bootstrap-select: index.md
- Usage: usage.md
- Examples: examples.md
- Options: options.md
- Methods: methods.md
