site_name: Bootstrap-select
site_description: A custom select for @twitter bootstrap using button dropdown.
repo_url: https://github.com/silviomoreto/bootstrap-select
theme: yeti
theme_dir: custom_theme
extra_css:
- //cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css
- css/custom.css
extra_javascript:
- //cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js
pages:
- ['index.md', 'Bootstrap-select']
- ['usage.md', 'Usage']
- ['examples.md', 'Examples']
- ['options.md', 'Options']
- ['methods.md', 'Methods']
